Bugfixes: match-mondo-sources-all-lexical.py - Bugfix: AttributeError: 'tuple' object has no attribute 'pop': wrong datatype for metadata was being passed to lexical_index_to_sssom() - Bugfix: Several other bugs in mondo-ingest, and upgrading OAK/sssom-py/curies to fix other bugs related to prefix maps. - Update: mondo.sssom.config.yml: Commented out duplicate prefix 'oio' - Update: prefixes.csv: Removed duplicate prefix oio - Update: Python requirements: Upgraded curies for bugfix involving get_prefixes(include_synonyms) - Update: Not bugfixes, but did some codestyle fixes: (i) converted regular comments to docstring, (ii) added missing docstring, (iii) renamed built-in 'input' param